flip tag and status options fields; add stub data; add option to fulfill and notify;
lightward/mechanic-tasks pull request #20
Opened 2021-01-30 10:37 UTC by tekhaus

Since this task runs on order update, I decided to just rely on the fulfillment (if option chosen) to cause another update and thus hitting the other branch that checks tags on the next task run, in lieu of getting overly complex with actions/perform or a custom event.

I purposely only try to fulfill order with NO prior fulfillments, so if an order is manually fulfilled and cancelled, and then tagged, it will not try to fulfill it again.

I wasn't sure whether it was useful to add an additional preview block so the fulfillment would evaluate. Let me know if I should.

Also, in the slack you advised against relying on the **task.shopify_api_version** values, but with these versioned REST calls this actually seems like a perfect use for them.

2021-01-30 10:39 UTC, tekhaus commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modernize "Manage fulfillment status using order tags"](https://trello.com/c/NdKovFiS/15-modernize-manage-fulfillment-status-using-order-tags)

2021-02-10 02:13 UTC, isaacbowen requested changes
> Since this task runs on order update, I decided to just rely on the fulfillment (if option chosen) to cause another update and thus hitting the other branch that checks tags on the next task run, in lieu of getting overly complex with actions/perform or a custom event.

This was an excellent opportunity to choose simplicity. Bravo. 👏 

> I purposely only try to fulfill order with NO prior fulfillments, so if an order is manually fulfilled and cancelled, and then tagged, it will not try to fulfill it again.

This is a good thing to include in the task documentation. Can you add that in? That (and the whitespace nit) is my only requested change - this is a _great_ contribution. 🙌 

> I wasn't sure whether it was useful to add an additional preview block so the fulfillment would evaluate. Let me know if I should.

I am also not sure. :D I'm okay with what you've chosen.

2021-02-10 02:13 UTC, isaacbowen commented on docs/manage-fulfillment-status-using-order-tags/script.liquid
> +            "/admin/api/{{ task.shopify_api_version }}/orders/{{ order.id }}/fulfillments/{{ fulfillment.id }}/events.json",
Huh, that _is_ clever. :D Nice.

2021-02-10 02:13 UTC, isaacbowen commented on docs/manage-fulfillment-status-using-order-tags/script.liquid
> +{% else%}
While you're in here for the documentation update (if you don't mind!), can you add a space on the other end of this `else`?

2021-02-10 18:22 UTC, merged