use-sequenced-action-runs-to-reduce-stages
lightward/mechanic-tasks pull request #5
Opened 2020-11-14 00:43 UTC by tekhaus

In the original task, the stage2 and stage3 preview blocks reassign the event object so that it can just call event.data.collection_id and get the passed collection id.

This reassignment prevents using event.preview blocks later within that event topic block [that stumped me for a bit], so I changed that up in order to have the second preview block in the stage2 topic appear after the logic to assign all_product_ids.
 
An initial approach I considered was to consolidate the preview blocks in stage2 at the top as a matter of convention, but seeing preview data unrelated to the action that initiated stage2 just seemed odd. Plus, I then had to do something dirty like this - {% assign all_product_ids = in_stock_product_ids | concat: out_of_stock_product_ids | default: event.data.ordered_product_ids %}.

2020-11-14 23:01 UTC, isaacbowen commented
:D All of that makes sense, yeah.

Since we're here, let's do this properly. You're right about moving event.preview blocks up as far as possible; for tasks that respond to several event topics, it feels best to me to do this _immediately after_ we've branched for a specific topic. Further, moving action blocks as far _down_ as possible is _also_ good. Combining both of those priorities, how does this structure look?

https://gist.github.com/isaacbowen/e6259dd38269777f283d59d3f33e4a89

Diff with your code: https://gist.github.com/isaacbowen/e6259dd38269777f283d59d3f33e4a89/revisions

(Not super sure where the right place is to render the very final `collectionUpdate` action; it should end up as close to the end of the task as possible while still being before the `collectionReorderProducts` actions.)

> This reassignment prevents using event.preview blocks later within that event topic block [that stumped me for a bit] [...]

haha, indeed. :D There's nothing sacred about this, though, so stubbing for `event.preview` is fine by me. ;) I do that in the code I linked above.

2020-11-16 19:10 UTC, tekhaus commented
> Since we're here, let's do this properly. You're right about moving event.preview blocks up as far as possible; for tasks that respond to several event topics, it feels best to me to do this _immediately after_ we've branched for a specific topic.

Sometimes I forget the basic tenet of quality task building... have the stub validate your task logic, don't use it to force the results you need in later actions if your logic should be doing that for you. Thank you for the direction.

2020-11-16 19:45 UTC, isaacbowen requested changes
I'm happy. :) Two whitespace nits, then let's get this merged.

2020-11-16 19:45 UTC, isaacbowen commented on docs/move-out-of-stock-products-to-the-end-of-a-collection/README.md
> +This task re-sorts your collections, beginning with the sort order of your choice (alphabetically, best selling first, etc), and then moving all out-of-stock products to the very end of the collectio
extraneous space at the end of this line

2020-11-16 19:45 UTC, isaacbowen commented on docs/move-out-of-stock-products-to-the-end-of-a-collection/script.liquid
> +
extraneous newline

2020-11-16 20:05 UTC, isaacbowen approved these changes

2020-11-16 20:07 UTC, merged