New task: Publish/unpublish products by tag
lightward/mechanic-tasks pull request #60
Opened 2021-08-27 22:50 UTC by tekhaus

To pair well with other tasks (such as https://tasks.mechanic.dev/auto-tag-out-of-stock-products), this task runs on product update to immediately publish/unpublish products.

Was a bit torn on whether to allow different sales channels to be configured with different tags, but decided that multiple instances of this task would be sufficient for that use case.

I also opted to not include a test mode, presuming that updating the tags on a few products would be test enough before running the full product catalog scan manually.

2021-08-27 23:20 UTC, isaacbowen requested changes
_Awesome_ - thank you thank you. :) Two small requests, then let's get this merged.

2021-08-27 23:20 UTC, isaacbowen commented on docs/README.md
> +* [Auto publish products to sales channels by tag](./auto-publish-products-to-sales-channels-by-tag)
Simplify to "Auto-publish products by tag" (applying that to the filename/slug as well).

2021-08-27 23:20 UTC, isaacbowen commented on docs/auto-publish-products-to-sales-channels-by-tag/script.liquid
> +{% assign publications_indexed_by_name = publications | index_by: "name" %}
Log this value, for debugging: `{% log available_publications: publications_indexed_by_name %}`, maybe. Small mistakes on sales channel names are common, and logging all the available ones helps when ironing out those config issues.

2021-08-29 18:31 UTC, tekhaus commented
New PR #61 created

2021-08-29 18:31 UTC, closed without merging