new task: auto-tag products with incoming inventory
lightward/mechanic-tasks pull request #78
Opened 2021-11-24 23:20 UTC by tekhaus

Development notes:
- The paginated query loop on inventory level change is for handling the maximum of 100 variants in conjunction with 100 locations (i.e. inventory levels). Technically, the Shopify location limit is 20 for PLUS shops, unless they specifically request more. I have seen 100 in the wild.

2021-11-24 23:20 UTC, tekhaus commented
![](https://github.trello.services/images/mini-trello-icon.png) [https://mechanic.canny.io/task-requests/p/auto-tag-incoming-products](https://trello.com/c/LbPzMxa3/45-https-mechaniccannyio-task-requests-p-auto-tag-incoming-products)

2021-11-26 16:55 UTC, mattsodomsky requested changes
@tekhaus awesome work :) This is an exciting task!! A few very minor touchups and I'll get this merged.

2021-11-26 16:55 UTC, mattsodomsky commented on docs/auto-tag-products-with-incoming-inventory/README.md
> +Tags: Auto-Tag, Bulk, Inventory, Products
add Transfer tag, you'll need to add here as well: https://github.com/lightward/mechanic-tasks/blob/main/lib/task_schema.json

2021-11-26 16:55 UTC, mattsodomsky commented on docs/auto-tag-products-with-incoming-inventory/script.liquid
> +  New task: Auto-tag products with incoming inventory
Remove comment :)

2021-11-27 01:13 UTC, mattsodomsky approved these changes
Looks great! thank you!

2021-11-27 01:14 UTC, merged