convert publishing and unpublishing of collection products to graphql
lightward/mechanic-tasks pull request #9
Opened 2020-11-30 07:30 UTC by tekhaus

2020-11-30 07:33 UTC, tekhaus commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modernize the publish-/unpublish-a-collection tasks](https://trello.com/c/YCSB2obP/9-modernize-the-publish-unpublish-a-collection-tasks)

2020-11-30 23:19 UTC, isaacbowen requested changes
Good! Thank you! :D One adjustment, then we're clear. 👍

2020-11-30 23:19 UTC, isaacbowen commented on docs/publish-a-certain-collection-daily/script.liquid
> +{% if collection == blank and event.preview == false %}
Nuance: `event.preview` is never false ([docs](https://docs.usemechanic.com/article/373-the-event-object)). It's either true, or the `event` object just doesn't have a `preview` property at all. I think the best way to express the intent here is `event.preview != true`.

2020-11-30 23:19 UTC, isaacbowen commented on docs/unpublish-a-certain-collection-daily/script.liquid
> +{% if collection == blank and event.preview == false %}
ditto

2020-12-01 01:21 UTC, isaacbowen approved these changes

2020-12-01 01:21 UTC, merged